export const LOGIN_USER_ALREADY_REGISTERED = 'LOGIN_USER_ALREADY_REGISTERED';
export type LOGIN_USER_ALREADY_REGISTERED = typeof LOGIN_USER_ALREADY_REGISTERED;
export const LOGIN_EMAIL_DOES_NOT_EXIST = 'LOGIN_EMAIL_DOES_NOT_EXIST';
export type LOGIN_EMAIL_DOES_NOT_EXIST = typeof LOGIN_EMAIL_DOES_NOT_EXIST;
export const LOGIN_BAD_PASSWORD = 'LOGIN_BAD_PASSWORD';
export type LOGIN_BAD_PASSWORD = typeof LOGIN_BAD_PASSWORD;

export type LOGIN_ERROR = LOGIN_USER_ALREADY_REGISTERED | LOGIN_EMAIL_DOES_NOT_EXIST | LOGIN_BAD_PASSWORD;
